const{test,expect}=require("@playwright/test")

test.skip("Positive Test Case",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/login")
    const email=page.locator("//input[@name='email']")
    const password=page.locator("//input[@name='password']")
    const logbtn=page.locator("//button[@name='Login']")
    const firstname=page.locator("//input[@name='firstName']")
    const lastname=page.locator("//input[@name='lastName']")
    const houseNumber=page.locator("//input[@name='houseNumber']")
    const address=page.locator("//input[@name='address2']")
    const province=page.locator("//div[text()='Sindh']")
    const city=page.locator("//div[text()='Karachi']")
    const area=page.locator("//div[text()='AB Sinia Colony']")
    const zipCode=page.locator("//input[@name='zipCode']")
    const phonenumber=page.locator("input[placeholder='923331111111'][value='+92']")
    const selecttype=page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-building fa-md ']")
    const submitaddress=page.locator("//button[@class=' style_yelloutlineCustomBtn__bH130 btn btn-primary']")
    await email.type("tanveersalim24@gmail.com")
    await password.type("Admin@12")
    await logbtn.click()
    await page.waitForTimeout(2000)
    await page.locator("//img[@class='style_imgFloatLeft__yPtNb d-none d-lg-inline']").click()
    await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-user-large fa-1x navbar-toggler-icon mr-2']").click()
    await page.locator("//button[@class='rounded-0 btn btn-outline-primary btn-sm']").click()
    await firstname.fill("rohan")
    await lastname.fill("rohan")
    await houseNumber.fill("PECHS")
    await address.click()
    await province.click()
    await city.click()
    await area.click()
    await zipCode.fill("543453")
    await phonenumber.fill("3361122876")
    await selecttype.click()
    await submitaddress.click()

})

test.skip("Negative1 Test Case",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/login")
    const email=page.locator("//input[@name='email']")
    const password=page.locator("//input[@name='password']")
    const logbtn=page.locator("//button[@name='Login']")
    const firstname=page.locator("//input[@name='firstName']")
    const lastname=page.locator("//input[@name='lastName']")
    const houseNumber=page.locator("//input[@name='houseNumber']")
    const address=page.locator("//input[@name='address2']")
    const province=page.locator("//div[text()='Sindh']")
    const city=page.locator("//div[text()='Karachi']")
    const area=page.locator("//div[text()='AB Sinia Colony']")
    const zipCode=page.locator("//input[@name='zipCode']")
    const phonenumber=page.locator("input[placeholder='923331111111'][value='+92']")
    const selecttype=page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-building fa-md ']")
    const submitaddress=page.locator("//button[@class=' style_yelloutlineCustomBtn__bH130 btn btn-primary']")
    const firstnameerrormessage=page.locator("//div[text()='Enter a first name']")
    const lastnameerrormessage=page.locator("//div[text()='Enter a last name.']")
    const housenumberrrormessage=page.locator("//div[text()='This address is too short.']")
    const zipcodeerrormessage=page.locator("//div[text()='Please enter valid postal code.']")
    const phonenumbererrormessage=page.locator("//div[text()='Please provide valid phone number']")
    await email.type("tanveersalim24@gmail.com")
    await password.type("Admin@12")
    await logbtn.click()
    await page.waitForTimeout(2000)
    await page.locator("//img[@class='style_imgFloatLeft__yPtNb d-none d-lg-inline']").click()
    await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-user-large fa-1x navbar-toggler-icon mr-2']").click()
    await page.locator("//button[@class='rounded-0 btn btn-outline-primary btn-sm']").click()
    await firstname.fill("")
    await lastname.fill("")
    await houseNumber.fill("")
    //await address.click()
    //await province.click()
    //await city.click()
    //await area.click()
    await zipCode.fill("")
    await phonenumber.fill("")
    await selecttype.click()
    await submitaddress.click()
    await expect.soft(firstnameerrormessage).toContainText("Enter a first name")
    await expect.soft(lastnameerrormessage).toContainText("Enter a last name")
    await expect.soft(housenumberrrormessage).toContainText("Enter a Address")
    await expect.soft(zipcodeerrormessage).toContainText("Please enter postal code.")
    await expect.soft(phonenumbererrormessage).toContainText("Please provide phone number")
})

test.skip("Negative2 Test Case",async function({page}){

    await page.goto("https://testing.ui.plentyz.pk/login")
    const email=page.locator("//input[@name='email']")
    const password=page.locator("//input[@name='password']")
    const logbtn=page.locator("//button[@name='Login']")
    const firstname=page.locator("//input[@name='firstName']")
    const lastname=page.locator("//input[@name='lastName']")
    const houseNumber=page.locator("//input[@name='houseNumber']")
    const address=page.locator("//input[@name='address2']")
    const province=page.locator("//div[text()='Sindh']")
    const city=page.locator("//div[text()='Karachi']")
    const area=page.locator("//div[text()='AB Sinia Colony']")
    const zipCode=page.locator("//input[@name='zipCode']")
    const phonenumber=page.locator("input[placeholder='923331111111'][value='+92']")
    const selecttype=page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-building fa-md ']")
    const submitaddress=page.locator("//button[@class=' style_yelloutlineCustomBtn__bH130 btn btn-primary']")
    await email.type("tanveersalim24@gmail.com")
    await password.type("Admin@12")
    await logbtn.click()
    await page.waitForTimeout(2000)
    await page.locator("//img[@class='style_imgFloatLeft__yPtNb d-none d-lg-inline']").click()
    await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-user-large fa-1x navbar-toggler-icon mr-2']").click()
    await page.locator("//button[@class='rounded-0 btn btn-outline-primary btn-sm']").click()
    await firstname.fill("123")
    await lastname.fill("23432")
    await houseNumber.fill("nasirabad rahimabad colony asdsdddsaddasdadasdadasd")
    await address.click()
    await province.click()
    await city.click()
    await area.click()
    await zipCode.fill("123")
    await phonenumber.fill("123")
    await selecttype.click()
    await submitaddress.click()
    await expect.soft(firstname).toHaveValue(/[A-Za-z]/)
    await expect.soft(lastname).toHaveValue(/[A-Za-z]/)
    await expect.soft(houseNumber).toHaveValue(/[a-zA-Z0-9]{30}/)
    await expect.soft(zipCode).toHaveValue(/[0-9]{5}/)
    await expect.soft(phonenumber).toHaveValue(/[[0-9]{10}]/)

})

test.skip("Positive2 Test Case",async function({page}){

    await page.goto("https://testing.ui.plentyz.pk/login")
    const email=page.locator("//input[@name='email']")
    const password=page.locator("//input[@name='password']")
    const logbtn=page.locator("//button[@name='Login']")
    const firstname=page.locator("//input[@name='firstName']")
    const lastname=page.locator("//input[@name='lastName']")
    const houseNumber=page.locator("//input[@name='houseNumber']")
    const address=page.locator("//input[@name='address2']")
    const province=page.locator("//div[text()='Sindh']")
    const city=page.locator("//div[text()='Karachi']")
    const area=page.locator("//div[text()='AB Sinia Colony']")
    const zipCode=page.locator("//input[@name='zipCode']")
    const phonenumber=page.locator("//input[@value='+92']")
    const selecttype=page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-building fa-md ']")
    const submitaddress=page.locator("//button[@class=' style_yelloutlineCustomBtn__bH130 btn btn-primary']")
    await email.type("tanveersalim24@gmail.com")
    await password.type("Admin@12")
    await logbtn.click()
    await page.waitForTimeout(2000)
    await page.locator("//img[@class='style_imgFloatLeft__yPtNb d-none d-lg-inline']").click()
    await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-user-large fa-1x navbar-toggler-icon mr-2']").click()
    await page.locator("//button[@class='rounded-0 btn btn-outline-primary btn-sm']").click()
    await firstname.fill("rohan")
    await lastname.fill("hussain")
    await houseNumber.fill("Nasirabad Rahimabad Colony Flat No J 58")
    await address.click()
    await province.click()
    await city.click()
    await area.click()
    await zipCode.fill("12345")
    await phonenumber.fill("3361122765")
    console.log("firstname: ",await firstname.inputValue())
    console.log("lastname: ",await lastname.inputValue())
    console.log("housenumber: ",await houseNumber.inputValue())
    console.log("completeaddress: ",await address.inputValue())
    await page.waitForTimeout(3000)
    console.log("zipcode: ",await zipCode.inputValue())
    console.log("phonenumber: ",await phonenumber.inputValue())
     await page.waitForTimeout(3000)
    await expect.soft(firstname).toHaveValue(/[A-Za-z]/)
    await expect.soft(lastname).toHaveValue(/[A-Za-z]/)
    await expect.soft(houseNumber).toHaveValue(/[a-zA-Z0-9]/)
    await expect.soft(address).toHaveValue(/[A-Za-z,]/)
    await expect.soft(zipCode).toHaveValue(/[0-9]{5}/)
    //await expect.soft(phonenumber).toHaveValue(/[[0-9-]{10}]/)
    await selecttype.click()
    await submitaddress.click()
    

})