const{test,expect}=require("@playwright/test")

test.skip("Positive Test Case",async function({page}){
    await pag.goto("https://testing.ui.plentyz.pk/login")
    await page.locator("//input[@name='email']").type("tanveersalim24@gmail.com")
    await page.locator("//input[@name='password']").type("Admin@11")
    await page.locator("//button[@name='Login']").click()
    await page.waitForTimeout(3000)
    await page.locator("//img[@class='style_imgFloatLeft__yPtNb d-none d-lg-inline']").click()
    await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-user-large fa-1x navbar-toggler-icon mr-2']").click()
    await page.locator("//button[@class='rounded-0 btn btn-outline-primary btn-sm']").click()
    await page.locator("//input[@name='firstName']").fill("rohan")
    await page.locator("//input[@name='lastName']").fill("rohan")
    await page.locator("//input[@name='houseNumber']").fill("PECHS")
    await page.locator("//input[@name='address2']").click()
    await page.locator("//div[text()='Sindh']").click()
    await page.locator("//div[text()='Karachi']").click()
    await page.locator("//div[text()='AB Sinia Colony']").click()
    await page.locator("//input[@name='zipCode']").fill("543453")
    await page.waitForTimeout(2000)
    //await page.locator("//input[@class='form-control invalid-number ']").fill("3361122876")
    await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-building fa-md ']").click()
    await page.locator("//button[@class=' style_yelloutlineCustomBtn__bH130 btn btn-primary']").click()

})

test.skip("Negative1 Test Case",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/login")
    await page.locator("//input[@name='email']").type("tanveersalim24@gmail.com")
    await page.locator("//input[@name='password']").type("Admin@11")
    await page.locator("//button[@name='Login']").click()
    await page.waitForTimeout(3000)
    await page.locator("//img[@class='style_imgFloatLeft__yPtNb d-none d-lg-inline']").click()
    await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-user-large fa-1x navbar-toggler-icon mr-2']").click()
    await page.locator("//button[@class='rounded-0 btn btn-outline-primary btn-sm']").click()
    await page.locator("//input[@name='firstName']").fill("")
    await page.locator("//input[@name='lastName']").fill("")
    await page.locator("//input[@name='houseNumber']").fill("")
    await page.locator("//input[@name='address2']").click()
    await page.locator("//div[text()='Sindh']").click()
    await page.locator("//div[text()='Karachi']").click()
    await page.locator("//div[text()='AB Sinia Colony']").click()
    await page.locator("//input[@name='zipCode']").fill("")
    await page.waitForTimeout(2000)         
    //await page.locator("//input[@class='form-control invalid-number ']").fill("3361122876")
    await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-building fa-md ']").click()
    await page.locator("//button[@class=' style_yelloutlineCustomBtn__bH130 btn btn-primary']").click()
    expect("//div[text()='Enter a first name']").toContain("Enter a first name")
    expect("//div[text()='Enter a last name']").toContain("Enter a last name")
    expect.soft("//div[text()='This address is too short.']").toContain("Enter a Street Address")
    expect.soft("//div[text()='Please enter valid postal code.']").toContain("Please enter postal code.")
    expect("//div[text()='Please provide valid phone number']").toContain("Please provide phone number")

})

test.skip("Negative2 Test Case",async function({page}){

    await page.goto("https://testing.ui.plentyz.pk/login")
    await page.locator("//input[@name='email']").type("tanveersalim24@gmail.com")
    await page.locator("//input[@name='password']").type("Admin@11")
    await page.locator("//button[@name='Login']").click()
    await page.waitForTimeout(3000)
    await page.locator("//img[@class='style_imgFloatLeft__yPtNb d-none d-lg-inline']").click()
    await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-user-large fa-1x navbar-toggler-icon mr-2']").click()
    await page.locator("//button[@class='rounded-0 btn btn-outline-primary btn-sm']").click()
    await page.locator("//input[@name='firstName']").fill("")
    await page.locator("//input[@name='lastName']").fill("")
    await page.locator("//input[@name='houseNumber']").fill("")
    await page.locator("//input[@name='address2']").click()
    await page.locator("//div[text()='Sindh']").click()
    await page.locator("//div[text()='Karachi']").click()
    await page.locator("//div[text()='AB Sinia Colony']").click()
    await page.locator("//input[@name='zipCode']").fill("")
    await page.waitForTimeout(2000)
    //await page.locator("//input[@class='form-control invalid-number ']").fill("3361122876")
    await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-building fa-md ']").click()
    await page.locator("//button[@class=' style_yelloutlineCustomBtn__bH130 btn btn-primary']").click()
    expect("//div[text()='Enter a first name']").toContain("Enter a first name")
    expect("//div[text()='Enter a last name']").toContain("Enter a last name")
    expect("//div[text()='This address is too short.']").toContain("Enter a Street Address")
    expect("//div[text()='Please enter valid postal code.']").toContain("Please enter postal code.")
    expect("//div[text()='Please provide valid phone number']").toContain("Please provide phone number")

})