const{test,expect}=require("@playwright/test")

test.skip("Postive Test Case",async function({page}){
await page.goto("https://testing.ui.plentyz.pk/contact-us")
const name=page.locator("//input[@name='name']")
const email=page.locator("//input[@name='email']")
const message=page.locator("//textarea[@name='message']")
const submitbtn=page.locator("//button[@class='style_blueCustomBtn__BPQFQ rounded btn btn-primary']")
await name.fill("ali")
await email.fill("rohan@gmail.com")
await message.fill("Hi There!")
await submitbtn.click()
})

test.skip("Negative1 Test Case",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/contact-us")
    const name=page.locator("//input[@name='name']")
    const email=page.locator("//input[@name='email']")
    const message=page.locator("//textarea[@name='message']")
    const nameerrormessage=page.locator("//div[text()='Name is required']")
    const emailerrormessage=page.locator("//div[text()='Please provide valid email']")
    const messageerror=page.locator("//div[text()='Please provide valid Message']")
    const submitbtn=page.locator("//button[@class='style_blueCustomBtn__BPQFQ rounded btn btn-primary']")
    await name.fill("")
    await email.fill("")
    await message.fill("")
    await submitbtn.click()
    await expect.soft(nameerrormessage).toContainText("Name is required")
    await expect.soft(emailerrormessage).toContainText("Please provide email")
    await expect.soft(messageerror).toContainText("Please provide Message")
    
})

test.skip("Negative2 Test Case",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/contact-us")
    const name=page.locator("//input[@name='name']")
    const email=page.locator("//input[@name='email']")
    const message=page.locator("//textarea[@name='message']")
    //const nameerrormessage=page.locator("//div[text()='Name is required']")
    const emailerrormessage=page.locator("//div[contains(@class,'px-xl-5 px-lg-5 px-2 col-xl-7 col-lg-6 col-md-12 col-sm-12 col-12')]//div[contains(@class,'invalid-feedback')][normalize-space()='Please provide valid email']")
    //const messageerror=page.locator("//div[text()='Please provide valid Message']")
    const submitbtn=page.locator("//button[@class='style_blueCustomBtn__BPQFQ rounded btn btn-primary']")
    await name.fill("rohan")
    await email.fill("tanveersalim")
    await message.fill("Hi There!")
    await submitbtn.click()
    await expect.soft(emailerrormessage).toContainText("Please provide valid email")
})

test.skip("Negative3 Test Case",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/contact-us")
    const name=page.locator("//input[@name='name']")
    const email=page.locator("//input[@name='email']")
    const message=page.locator("//textarea[@name='message']")
    //const nameerrormessage=page.locator("//div[text()='Name is required']")
    //const emailerrormessage=page.locator("//div[contains(@class,'px-xl-5 px-lg-5 px-2 col-xl-7 col-lg-6 col-md-12 col-sm-12 col-12')]//div[contains(@class,'invalid-feedback')][normalize-space()='Please provide valid email']")
    //const messageerror=page.locator("//div[text()='Please provide valid Message']")
    const submitbtn=page.locator("//button[@class='style_blueCustomBtn__BPQFQ rounded btn btn-primary']")
    await name.fill("123")
    await email.fill("tanveersalim24@gmail.com")
    await message.fill("Hi There!")
    await expect.soft(name).toHaveValue(/[A-Za-z]/)
    await submitbtn.click()
    
})