const{test,expect}=require("@playwright/test")

test.skip("Postive Test Case",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/login")
    await page.locator("//input[@name='email']").type("tanveersalim24@gmail.com")
    await page.locator("//input[@name='password']").type("Admin@12")
    await page.locator("//button[@name='Login']").click()
    await page.waitForTimeout(3000)
    await page.locator("//img[@class='style_imgFloatLeft__yPtNb d-none d-lg-inline']").click()
    await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-user-large fa-1x navbar-toggler-icon mr-2']").click()
    await page.locator("//button[@class='rounded-0 btn btn-success']").click()
    await page.locator("//input[@name='oldPassword']").fill("Admin@12")
    await page.locator("//input[@name='password']").fill("Admin@11")
    await page.locator("//input[@name='confirmPassword']").fill("Admin@11")
    await page.locator("//button[text()='Update']").click()
    await page.locator("//img[@class='style_imgFloatLeft__yPtNb d-none d-lg-inline']").click()
    await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-right-from-bracket fa-1x navbar-toggler-icon mr-2']").click()
    await page.goto("https://testing.ui.plentyz.pk/login")
    await page.locator("//input[@name='email']").type("tanveersalim24@gmail.com")
    await page.locator("//input[@name='password']").type("Admin@11")
    await page.locator("//button[@name='Login']").click()
})

test.skip("Negative1 Test Case",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/login")
    await page.locator("//input[@name='email']").type("tanveersalim24@gmail.com")
    await page.locator("//input[@name='password']").type("Admin@11")
    await page.locator("//button[@name='Login']").click()
    await page.waitForTimeout(3000)
    await page.locator("//img[@class='style_imgFloatLeft__yPtNb d-none d-lg-inline']").click()
    await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-user-large fa-1x navbar-toggler-icon mr-2']").click()
    await page.locator("//button[@class='rounded-0 btn btn-success']").click()
    await page.locator("//input[@name='oldPassword']").fill("")
    await page.locator("//input[@name='password']").fill("")
    await page.locator("//input[@name='confirmPassword']").fill("")
    await page.locator("//button[text()='Update']").click()
   expect("//div[text()='Password is invalid']").toContain("Password is required")
   expect("//div[text()='Password is required']").toContain("Password is required")
})

test.skip("Negative2 Test Case",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/login")
    await page.locator("//input[@name='email']").type("tanveersalim24@gmail.com")
    await page.locator("//input[@name='password']").type("Admin@11")
    await page.locator("//button[@name='Login']").click()
    await page.waitForTimeout(3000)
    await page.locator("//img[@class='style_imgFloatLeft__yPtNb d-none d-lg-inline']").click()
    await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-user-large fa-1x navbar-toggler-icon mr-2']").click()
    await page.locator("//button[@class='rounded-0 btn btn-success']").click()
    await page.locator("//input[@name='oldPassword']").fill("Admin@11")
    await page.locator("//input[@name='password']").fill("Admin@12")
    await page.locator("//input[@name='confirmPassword']").fill("Admin@13")
    await page.locator("//button[text()='Update']").click()
   expect("//div[text()='Confirm Password Doesn't Match']").toContain("Confirm Password Doesn't Match")
  
})

test.skip("Negative3 Test Case",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/login")
    await page.locator("//input[@name='email']").type("tanveersalim24@gmail.com")
    await page.locator("//input[@name='password']").type("Admin@11")
    await page.locator("//button[@name='Login']").click()
    await page.waitForTimeout(3000)
    await page.locator("//img[@class='style_imgFloatLeft__yPtNb d-none d-lg-inline']").click()
    await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-user-large fa-1x navbar-toggler-icon mr-2']").click()
    await page.locator("//button[@class='rounded-0 btn btn-success']").click()
    await page.locator("//input[@name='oldPassword']").fill("Admin@11")
    await page.locator("//input[@name='password']").fill("Admin@")
    await page.locator("//input[@name='confirmPassword']").fill("")
    await page.locator("//button[text()='Update']").click()
   expect("//div[text()='At least 8 characters and maximum 16 characters']").toContain("At least 8 characters and maximum 16 characters")
  
})