const{test,expect}=require("@playwright/test")

test.skip("Beauty and Grooming",async function({page}){
await page.goto("https://testing.ui.plentyz.pk")
const selectcategory=page.locator("//ul[@class='style_listGroup__Mpv9x list-group']/li[2]")
const discountedproduct=page.locator("//select[@class='custom-select custom-select-sm']")
const lowtohighprice=page.locator("//select[@class='custom-select custom-select-sm']")
const hightolowprice=page.locator("//select[@class='custom-select custom-select-sm']")
const lowestrank=page.locator("//select[@class='custom-select custom-select-sm']")
const highestrank=page.locator("//select[@class='custom-select custom-select-sm']")

await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-bars fa-1x mr-2']").click()
await page.waitForTimeout(3000)
await selectcategory.click()
await page.waitForTimeout("7000")
await discountedproduct.selectOption("Discount Products")
await page.waitForTimeout(3000)
await lowtohighprice.selectOption("Low to High Price")
await page.waitForTimeout(3000)
await hightolowprice.selectOption("High to Low Price")
await page.waitForTimeout(3000)
await lowestrank.selectOption("Lowest Rank")
await page.waitForTimeout(3000)
await highestrank.selectOption("Highest Rank")
await page.waitForTimeout(3000)

})