const{test,expect}=require("@playwright/test")

test.skip("Positive Test Case", async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/login")
    const email=page.locator("//input[@name='email']")
    const password=page.locator("//input[@name='password']")
    const logbtn=page.locator("//button[@name='Login']")
    const reviewtitle=page.locator("//input[@placeholder='Enter review title']")
    const review=page.locator("//textarea[@placeholder='Enter review']")
    const uploadimage=page.locator("//input[@id='pickImage']")
    const submitreviewbtn=page.locator("//button[@class='rounded-0 btn btn-success']")
    await email.type("tanveersalim24@gmail.com")
    await password.type("Admin@11")
    await logbtn.click()
    await page.waitForTimeout(3000)
    await page.goto("https://testing.ui.plentyz.pk/products/color-studio-gel-like-nail-polish-21-daisy-12/3014")
    await page.waitForTimeout(3000)
    await page.locator("//button[@class='float-right btn btn-primary']").click()
    await page.locator("tbody tr span:nth-child(2)").click()
    await reviewtitle.fill("Nice Product")
    await review.fill("Hi This product is great")
    await page.waitForTimeout(3000)
    await uploadimage.setInputFiles("upload/coupon.PNG")
    await page.waitForTimeout(3000)
    await submitreviewbtn.click()
})

test.skip("Negative1 Test Case", async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/login")
    const email=page.locator("//input[@name='email']")
    const password=page.locator("//input[@name='password']")
    const logbtn=page.locator("//button[@name='Login']")
    const reviewtitle=page.locator("//input[@placeholder='Enter review title']")
    const review=page.locator("//textarea[@placeholder='Enter review']")
    const uploadimage=page.locator("//input[@id='pickImage']")
    const submitreviewbtn=page.locator("//button[@class='rounded-0 btn btn-success']")
    const reviewtitleerrormessage=page.locator("//div[text()='Please write more than 5 characters']")
    const reviewerrormessage=page.locator("//div[text()='Please write more than 5 characters']")
    await email.type("tanveersalim24@gmail.com")
    await password.type("Admin@11")
    await logbtn.click()
    await page.waitForTimeout(3000)
    await page.goto("https://testing.ui.plentyz.pk/products/color-studio-gel-like-nail-polish-21-daisy-12/3014")
    await page.waitForTimeout(3000)
    await page.locator("//button[@class='float-right btn btn-primary']").click()
    await page.locator("tbody tr span:nth-child(2)").click()
    await reviewtitle.fill("")
    await review.fill("")
    await page.waitForTimeout(3000)
    await uploadimage.setInputFiles("upload/coupon.PNG")
    await page.waitForTimeout(3000)
    await submitreviewbtn.click()
    expect.soft(reviewtitleerrormessage).toContain("Please Enter Review Title")
    expect.soft(reviewerrormessage).toContain("Please Enter Review Message")


    
})

test.skip("Negative2 Test Case", async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/login")
    const email=page.locator("//input[@name='email']")
    const password=page.locator("//input[@name='password']")
    const logbtn=page.locator("//button[@name='Login']")
    const reviewtitle=page.locator("//input[@placeholder='Enter review title']")
    const review=page.locator("//textarea[@placeholder='Enter review']")
    const uploadimage=page.locator("//input[@id='pickImage']")
    const submitreviewbtn=page.locator("//button[@class='rounded-0 btn btn-success']")
    const reviewtitleerrormessage=page.locator("//div[text()='Please write more than 5 characters']")
    const reviewerrormessage=page.locator("//div[text()='Please write more than 5 characters']")
    await email.type("tanveersalim24@gmail.com")
    await password.type("Admin@11")
    await logbtn.click()
    await page.waitForTimeout(3000)
    await page.goto("https://testing.ui.plentyz.pk/products/color-studio-gel-like-nail-polish-21-daisy-12/3014")
    await page.waitForTimeout(3000)
    await page.locator("//button[@class='float-right btn btn-primary']").click()
    await page.locator("tbody tr span:nth-child(2)").click()
    await reviewtitle.fill("eee")
    await review.fill("eee")
    await page.waitForTimeout(3000)
    await uploadimage.setInputFiles("upload/coupon.PNG")
    await page.waitForTimeout(3000)
    await submitreviewbtn.click()
    expect.soft(reviewtitleerrormessage).toHaveValue(/[A-Za-z0-9@]{5}/)
    expect.soft(reviewerrormessage).toHaveValue(/[A-Za-z0-9@]{5}/)
})