const{test,expect}=require("@playwright/test")

test.skip("Positive Test Case", async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/login")
    await page.locator("//input[@name='email']").type("tanveersalim24@gmail.com")
    await page.locator("//input[@name='password']").type("Admin@11")
    await page.locator("//button[@name='Login']")
    await page.waitForTimeout(3000)
    await page.goto("https://testing.ui.plentyz.pk/products/color-studio-gel-like-nail-polish-21-daisy-12/3014")
    await page.waitForTimeout(3000)
    await page.locator("//button[@class='float-right btn btn-primary']").click()
    await page.locator("tbody tr span:nth-child(2)").click()
    await page.locator("//input[@placeholder='Enter review title']").fill("Nice Product")
    await page.locator("//textarea[@placeholder='Enter review']").fill("Hi This product is great")
    await page.waitForTimeout(3000)
    await page.locator("//input[@id='pickImage']").setInputFiles("upload/coupon.PNG")
    await page.waitForTimeout(3000)
    await page.locator("//button[@class='rounded-0 btn btn-success']").click()
})

test.skip("Negative1 Test Case", async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/login")
    await page.locator("//input[@name='email']").type("tanveersalim24@gmail.com")
    await page.locator("//input[@name='password']").type("Admin@11")
    await page.locator("//button[@name='Login']").click()
    await page.waitForTimeout(3000)
    await page.goto("https://testing.ui.plentyz.pk/products/color-studio-gel-like-nail-polish-21-daisy-12/3014")
    await page.waitForTimeout(3000)
    await page.locator("//button[@class='float-right btn btn-primary']").click()
    await page.locator("tbody tr span:nth-child(4)").click()
    await page.locator("//input[@placeholder='Enter review title']").fill("")
    await page.locator("//textarea[@placeholder='Enter review']").fill("")
    await page.waitForTimeout(3000)
    //await page.locator("//input[@id='pickImage']").setInputFiles("upload/coupon.PNG")
    await page.locator("//button[@class='rounded-0 btn btn-success']").click()
    expect.soft("//div[text()='Please write more than 5 characters']").toContain("Please Enter Review Title")
    expect.soft("//div[text()='Please write more than 5 characters']").toContain("Please Enter Review Message")
})

test.skip("Negative2 Test Case", async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/login")
    await page.locator("//input[@name='email']").type("tanveersalim24@gmail.com")
    await page.locator("//input[@name='password']").type("Admin@11")
    await page.locator("//button[@name='Login']").click()
    await page.waitForTimeout(3000)
    await page.goto("https://testing.ui.plentyz.pk/products/color-studio-gel-like-nail-polish-21-daisy-12/3014")
    await page.waitForTimeout(3000)
    await page.locator("//button[@class='float-right btn btn-primary']").click()
    await page.locator("tbody tr span:nth-child(4)").click()
    await page.locator("//input[@placeholder='Enter review title']").fill("eeee")
    await page.locator("//textarea[@placeholder='Enter review']").fill("eeee")
    await page.waitForTimeout(3000)
    //await page.locator("//input[@id='pickImage']").setInputFiles("upload/coupon.PNG")
    await page.locator("//button[@class='rounded-0 btn btn-success']").click()
    expect.soft("//div[text()='Please write more than 5 characters']").toContain("Please write more than 5 characters")
    expect.soft("//div[text()='Please write more than 5 characters']").toContain("Please write more than 5 characters")
})