const{test,expect}=require('@playwright/test')

test.skip("Postive Test Case",async function({page}){
await page.goto("https://testing.ui.plentyz.pk/registration")
const fullname=page.locator("//input[@name='fullName']")
const email=page.locator("//input[@name='email']")
const phone= page.locator("//input[@type='tel']")
const password=page.locator("//input[@name='password']")
const confirmPassword=page.locator("//input[@name='confirmPassword']")
const signup=page.locator("//button[@class='style_customBtn__HXt9M rounded-0 btn btn-primary']")
await fullname.fill("Zainali")
await email.fill("Zainali123456@gmail.com")
await phone.fill("3361122345")
await password.fill("Admin@12")
await confirmPassword.fill("Admin@12")
await page.waitForTimeout(10000)
await signup.click()
})

test.skip("Negative1 Test Case",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/registration")
    const fullname=page.locator("//input[@name='fullName']")
    const email=page.locator("//input[@name='email']")
    const phone= page.locator("//input[@type='tel']")
    const password=page.locator("//input[@name='password']")
    const confirmPassword=page.locator("//input[@name='confirmPassword']")
    const signup=page.locator("//button[@class='style_customBtn__HXt9M rounded-0 btn btn-primary']")
    const fullnameerrormessage=page.locator("//div[text()='Please provide valid name']")
    const emailerrormessage=page.locator("//div[text()='Please provide valid email']")
    const phoneerrormessage=page.locator("//div[text()='Please provide valid phone number']")
    const passworderrormessage=page.locator("//div[text()='Password is required']")
    //const confirmpassworderrormessage=page.locator("//div[text()='Please provide valid name']")
    await fullname.fill("")
    await email.fill("")
    await phone.fill("")
    await password.fill("")
    await confirmPassword.fill("")
    await expect.soft(fullnameerrormessage).toContainText("Please provide name")
    await expect.soft(emailerrormessage).toContainText("Please provide email")
    await expect.soft(phoneerrormessage).toContainText("Please provide phone number")
    await expect.soft(passworderrormessage).toContainText("Password is required")
    await page.waitForTimeout(10000)
    await signup.click()
})

test.skip("Negative2 Test Case",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/registration")
    const fullname=page.locator("//input[@name='fullName']")
    const email=page.locator("//input[@name='email']")
    const phone= page.locator("//input[@type='tel']")
    const password=page.locator("//input[@name='password']")
    const confirmPassword=page.locator("//input[@name='confirmPassword']")
    const signup=page.locator("//button[@class='style_customBtn__HXt9M rounded-0 btn btn-primary']")
    await fullname.fill("232")
    await email.fill("ASDAS")
    await phone.fill("123")
    await password.fill("Admin")
    await confirmPassword.fill("Admin")
    await expect.soft(fullname).toHaveValue(/[a-zA-Z]/)
    await expect.soft(email).toHaveValue(/[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/)
    await expect.soft(phone).toHaveValue(/[0-9]{10}/)
    await expect.soft(password).toHaveValue(/[a-zA-Z0-9]{8}/)
    await page.waitForTimeout(10000)
    await signup.click()
})

test.skip("Negative3 Test Case",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/registration")
    const fullname=page.locator("//input[@name='fullName']")
    const email=page.locator("//input[@name='email']")
    const phone= page.locator("//input[@type='tel']")
    const password=page.locator("//input[@name='password']")
    const confirmPassword=page.locator("//input[@name='confirmPassword']")
    const confirmPassworderrormessage=page.locator("//div[@class='style_inValidConfirmPassword__veO+0']")
    const signup=page.locator("//button[@class='style_customBtn__HXt9M rounded-0 btn btn-primary']")
    await fullname.fill("rohan")
    await email.fill("rohan@gmail.com")
    await phone.fill("1234567890")
    await password.fill("Admin123")
    await confirmPassword.fill("Admin124")
    await expect.soft(fullname).toHaveValue(/[a-zA-Z]/)
    await expect.soft(email).toHaveValue(/[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/)
    await expect.soft(phone).toHaveValue(/[0-9]{10}/)
    await expect.soft(password).toHaveValue(/[a-zA-Z0-9]{8}/)
    await expect.soft(confirmPassworderrormessage).toContainText("Confirm Password Doesn't Match")
    await page.waitForTimeout(10000)
    await signup.click()
})

            
test.skip("Positive2 Test Case",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/registration")
    const fullname=page.locator("//input[@name='fullName']")
    const email=page.locator("//input[@name='email']")
    const phone= page.locator("//input[@type='tel']")
    const password=page.locator("//input[@name='password']")
    const confirmPassword=page.locator("//input[@name='confirmPassword']")
    const signup=page.locator("//button[@class='style_customBtn__HXt9M rounded-0 btn btn-primary']")
    await fullname.fill("rohan")
    await email.fill("rohan@gmail.com")
    await phone.fill("1234567890")
    await password.fill("Admin123")
    await confirmPassword.fill("Admin124")
    await expect.soft(fullname).toHaveValue(/[a-zA-Z]/)
    await expect.soft(email).toHaveValue(/[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/)
    await expect.soft(phone).toHaveValue(/[0-9]{10}/)
    await expect.soft(password).toHaveValue(/[a-zA-Z0-9]{8}/)
    await expect.soft(confirmPassword).toHaveValue(/[a-zA-Z0-9]{8}/)
    await page.waitForTimeout(10000)
    await signup.click()
})

                
test.skip("Negative5 Test Case",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/registration")
    const fullname=page.locator("//input[@name='fullName']")
    const email=page.locator("//input[@name='email']")
    const phone= page.locator("//input[@type='tel']")
    const password=page.locator("//input[@name='password']")
    const confirmPassword=page.locator("//input[@name='confirmPassword']")
    const passworderrormessage=page.locator("//div[text()='At least 8 characters and maximum 16 characters']")
    const signup=page.locator("//button[@class='style_customBtn__HXt9M rounded-0 btn btn-primary']")
    await fullname.fill("rohan")
    await email.fill("rohan@gmail.com")
    await phone.fill("1234567890")
    await password.fill("Admin1")
    await confirmPassword.fill("Admin1")
    await expect.soft(fullname).toHaveValue(/[a-zA-Z]/)
    await expect.soft(email).toHaveValue(/[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/)
    await expect.soft(phone).toHaveValue(/[0-9]{10}/)
    await expect.soft(passworderrormessage).toContainText("At least 8 characters and maximum 16 characters")
    await expect.soft(confirmPassword).toHaveValue(/[a-zA-Z0-9]{8}/)
    await page.waitForTimeout(10000)
    await signup.click()

})

                    
                    

    