const{test,expect}=require('@playwright/test')

test.skip("spin wheel",async function({page}){
    await page.goto("https://testing.ui.plentyz.pk/login")
    const email=page.locator("//input[@name='email']")
    const password=page.locator("//input[@name='password']")
    const logbtn=page.locator("//button[@class='style_customBtn1__cgP1R btn btn-primary btn-block']")
    const spinwheelmodal=page.locator("//img[@class='giftBox']")
    const taptospin=page.locator("//button[@class='style_spinButton__xtbLU btn btn-primary']")
    await email.fill("tanveersalim24@gmail.com")
    await password.fill("Admin@11")
    await logbtn.click()
    await page.waitForTimeout(3000)
    await spinwheelmodal.click()
    await page.waitForTimeout(2000)
    await taptospin.click()
    await page.waitForTimeout(10000)
})