const{test,expect}=require("@playwright/test")

test.skip("wishlist",async function({page}){
await page.goto("https://testing.ui.plentyz.pk/login")
const email=page.locator("//input[@name='email']")
const password=page.locator("//input[@name='password']")
const logbtn=page.locator("//button[@name='Login']")
await email.type("tanveersalim24@gmail.com")
await password.type("Admin@12")
await logbtn.click()
await page.waitForTimeout(2000)
await page.goto("https://testing.ui.plentyz.pk/products/sac-professional-beard-shampoo-soap-bar/3267")
await page.waitForTimeout(3000)
await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-heart fa-2x style_wishListHeart__G7bS-']").click()
await page.waitForTimeout(2000)
await page.locator("//img[@class='style_imgFloatLeft__yPtNb d-none d-lg-inline']").click()
await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-gift fa-1x navbar-toggler-icon mr-2']").click()
await page.locator("//button[@class='rounded-0 btn btn-danger btn-1x']").click()
await page.locator("//button[@class='swal2-confirm swal2-styled swal2-default-outline']").click()
await page.locator("//img[@class='style_imgFloatLeft__yPtNb d-none d-lg-inline']").click()
await page.locator("//*[local-name()='svg' and @class='svg-inline--fa fa-right-from-bracket fa-1x navbar-toggler-icon mr-2']").click()
await page.waitForTimeout(3000)
})